deploy_tasks:
  development:
    before_deploy:
      - "exit 100"
      - "npm install"
      - "npm run gulp -- compile"
    after_deploy: |
      drush -y updb --cache-clear=0 2>&1
      drush -y cr 2>&1
  production:
    before_deploy: 
      - echo before_deploy
    after_deploy:
      - echo after_deploy
shared:
  production:
    - src: files
      dst: sites/default/files
