deploy_tasks:
  development:
    before_deploy:
      - "npm install"
      - "npm run gulp -- compile"
    after_deploy: |
      drush -y updb --cache-clear=0 2>&1
      drush -y cr 2>&1
  production:
    before_deploy: |
      npm install 2>&1 
      npm run gulp -- build 2>&1
      rm -rf node_modules 2>&1
    after_deploy: |
      drush -y updb --cache-clear=0 2>&1
      drush -y cr 2>&1
shared:
  production:
    - src: files
      dst: sites/default/files
